// Generated by rstantools.  Do not edit by hand.

/*
    mvgamHMC is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    mvgamHMC is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with mvgamHMC.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_multresponse_semipar_array_mixed_discrete_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_multresponse_semipar_array_mixed_discrete");
    reader.add_event(266, 264, "end", "model_multresponse_semipar_array_mixed_discrete");
    return reader;
}
#include <stan_meta_header.hpp>
class model_multresponse_semipar_array_mixed_discrete
  : public stan::model::model_base_crtp<model_multresponse_semipar_array_mixed_discrete> {
private:
        int N;
        int p;
        int q;
        int r;
        int nk;
        int ny;
        std::vector<std::vector<int> > y;
        matrix_d X;
        int max_col;
        std::vector<int> zvars;
        matrix_d Z;
        int qr;
        int qrsplit;
        int famnum;
        int linknum;
        std::vector<int> betanum;
        int beta_max_params;
        matrix_d beta_param;
        std::vector<int> lambdanum;
        int lambda_max_params;
        matrix_d lambda_param;
        matrix_d Q_x;
        matrix_d R_x;
        matrix_d R_x_inverse;
        matrix_d Q_z;
        matrix_d R_z;
        matrix_d R_z_inverse;
        std::vector<matrix_d> qz;
        std::vector<matrix_d> rz;
        std::vector<matrix_d> rzinv;
public:
    model_multresponse_semipar_array_mixed_discrete(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_multresponse_semipar_array_mixed_discrete(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_multresponse_semipar_array_mixed_discrete_namespace::model_multresponse_semipar_array_mixed_discrete";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 5;
            context__.validate_dims("data initialization", "N", "int", context__.to_vec());
            N = int(0);
            vals_i__ = context__.vals_i("N");
            pos__ = 0;
            N = vals_i__[pos__++];
            check_greater_or_equal(function__, "N", N, 0);
            current_statement_begin__ = 7;
            context__.validate_dims("data initialization", "p", "int", context__.to_vec());
            p = int(0);
            vals_i__ = context__.vals_i("p");
            pos__ = 0;
            p = vals_i__[pos__++];
            check_greater_or_equal(function__, "p", p, 0);
            current_statement_begin__ = 9;
            context__.validate_dims("data initialization", "q", "int", context__.to_vec());
            q = int(0);
            vals_i__ = context__.vals_i("q");
            pos__ = 0;
            q = vals_i__[pos__++];
            check_greater_or_equal(function__, "q", q, 0);
            current_statement_begin__ = 11;
            context__.validate_dims("data initialization", "r", "int", context__.to_vec());
            r = int(0);
            vals_i__ = context__.vals_i("r");
            pos__ = 0;
            r = vals_i__[pos__++];
            check_greater_or_equal(function__, "r", r, 0);
            current_statement_begin__ = 13;
            context__.validate_dims("data initialization", "nk", "int", context__.to_vec());
            nk = int(0);
            vals_i__ = context__.vals_i("nk");
            pos__ = 0;
            nk = vals_i__[pos__++];
            check_greater_or_equal(function__, "nk", nk, 0);
            current_statement_begin__ = 14;
            context__.validate_dims("data initialization", "ny", "int", context__.to_vec());
            ny = int(0);
            vals_i__ = context__.vals_i("ny");
            pos__ = 0;
            ny = vals_i__[pos__++];
            check_greater_or_equal(function__, "ny", ny, 0);
            current_statement_begin__ = 16;
            validate_non_negative_index("y", "N", N);
            validate_non_negative_index("y", "ny", ny);
            context__.validate_dims("data initialization", "y", "int", context__.to_vec(N,ny));
            y = std::vector<std::vector<int> >(N, std::vector<int>(ny, int(0)));
            vals_i__ = context__.vals_i("y");
            pos__ = 0;
            size_t y_k_0_max__ = N;
            size_t y_k_1_max__ = ny;
            for (size_t k_1__ = 0; k_1__ < y_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < y_k_0_max__; ++k_0__) {
                    y[k_0__][k_1__] = vals_i__[pos__++];
                }
            }
            current_statement_begin__ = 19;
            validate_non_negative_index("X", "N", N);
            validate_non_negative_index("X", "p", p);
            context__.validate_dims("data initialization", "X", "matrix_d", context__.to_vec(N,p));
            X = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(N, p);
            vals_r__ = context__.vals_r("X");
            pos__ = 0;
            size_t X_j_2_max__ = p;
            size_t X_j_1_max__ = N;
            for (size_t j_2__ = 0; j_2__ < X_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < X_j_1_max__; ++j_1__) {
                    X(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 21;
            context__.validate_dims("data initialization", "max_col", "int", context__.to_vec());
            max_col = int(0);
            vals_i__ = context__.vals_i("max_col");
            pos__ = 0;
            max_col = vals_i__[pos__++];
            current_statement_begin__ = 23;
            validate_non_negative_index("zvars", "(q + 1)", (q + 1));
            context__.validate_dims("data initialization", "zvars", "int", context__.to_vec((q + 1)));
            zvars = std::vector<int>((q + 1), int(0));
            vals_i__ = context__.vals_i("zvars");
            pos__ = 0;
            size_t zvars_k_0_max__ = (q + 1);
            for (size_t k_0__ = 0; k_0__ < zvars_k_0_max__; ++k_0__) {
                zvars[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 25;
            validate_non_negative_index("Z", "N", N);
            validate_non_negative_index("Z", "nk", nk);
            context__.validate_dims("data initialization", "Z", "matrix_d", context__.to_vec(N,nk));
            Z = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(N, nk);
            vals_r__ = context__.vals_r("Z");
            pos__ = 0;
            size_t Z_j_2_max__ = nk;
            size_t Z_j_1_max__ = N;
            for (size_t j_2__ = 0; j_2__ < Z_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < Z_j_1_max__; ++j_1__) {
                    Z(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 30;
            context__.validate_dims("data initialization", "qr", "int", context__.to_vec());
            qr = int(0);
            vals_i__ = context__.vals_i("qr");
            pos__ = 0;
            qr = vals_i__[pos__++];
            check_greater_or_equal(function__, "qr", qr, 0);
            check_less_or_equal(function__, "qr", qr, 1);
            current_statement_begin__ = 32;
            context__.validate_dims("data initialization", "qrsplit", "int", context__.to_vec());
            qrsplit = int(0);
            vals_i__ = context__.vals_i("qrsplit");
            pos__ = 0;
            qrsplit = vals_i__[pos__++];
            check_greater_or_equal(function__, "qrsplit", qrsplit, 0);
            check_less_or_equal(function__, "qrsplit", qrsplit, 1);
            current_statement_begin__ = 35;
            context__.validate_dims("data initialization", "famnum", "int", context__.to_vec());
            famnum = int(0);
            vals_i__ = context__.vals_i("famnum");
            pos__ = 0;
            famnum = vals_i__[pos__++];
            check_greater_or_equal(function__, "famnum", famnum, 1);
            check_less_or_equal(function__, "famnum", famnum, 3);
            current_statement_begin__ = 37;
            context__.validate_dims("data initialization", "linknum", "int", context__.to_vec());
            linknum = int(0);
            vals_i__ = context__.vals_i("linknum");
            pos__ = 0;
            linknum = vals_i__[pos__++];
            current_statement_begin__ = 50;
            validate_non_negative_index("betanum", "((p * r) + 1)", ((p * r) + 1));
            context__.validate_dims("data initialization", "betanum", "int", context__.to_vec(((p * r) + 1)));
            betanum = std::vector<int>(((p * r) + 1), int(0));
            vals_i__ = context__.vals_i("betanum");
            pos__ = 0;
            size_t betanum_k_0_max__ = ((p * r) + 1);
            for (size_t k_0__ = 0; k_0__ < betanum_k_0_max__; ++k_0__) {
                betanum[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 51;
            context__.validate_dims("data initialization", "beta_max_params", "int", context__.to_vec());
            beta_max_params = int(0);
            vals_i__ = context__.vals_i("beta_max_params");
            pos__ = 0;
            beta_max_params = vals_i__[pos__++];
            current_statement_begin__ = 52;
            validate_non_negative_index("beta_param", "(p * r)", (p * r));
            validate_non_negative_index("beta_param", "beta_max_params", beta_max_params);
            context__.validate_dims("data initialization", "beta_param", "matrix_d", context__.to_vec((p * r),beta_max_params));
            beta_param = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>((p * r), beta_max_params);
            vals_r__ = context__.vals_r("beta_param");
            pos__ = 0;
            size_t beta_param_j_2_max__ = beta_max_params;
            size_t beta_param_j_1_max__ = (p * r);
            for (size_t j_2__ = 0; j_2__ < beta_param_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < beta_param_j_1_max__; ++j_1__) {
                    beta_param(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 55;
            validate_non_negative_index("lambdanum", "((q * r) + 1)", ((q * r) + 1));
            context__.validate_dims("data initialization", "lambdanum", "int", context__.to_vec(((q * r) + 1)));
            lambdanum = std::vector<int>(((q * r) + 1), int(0));
            vals_i__ = context__.vals_i("lambdanum");
            pos__ = 0;
            size_t lambdanum_k_0_max__ = ((q * r) + 1);
            for (size_t k_0__ = 0; k_0__ < lambdanum_k_0_max__; ++k_0__) {
                lambdanum[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 56;
            context__.validate_dims("data initialization", "lambda_max_params", "int", context__.to_vec());
            lambda_max_params = int(0);
            vals_i__ = context__.vals_i("lambda_max_params");
            pos__ = 0;
            lambda_max_params = vals_i__[pos__++];
            current_statement_begin__ = 57;
            validate_non_negative_index("lambda_param", "(q * r)", (q * r));
            validate_non_negative_index("lambda_param", "lambda_max_params", lambda_max_params);
            context__.validate_dims("data initialization", "lambda_param", "matrix_d", context__.to_vec((q * r),lambda_max_params));
            lambda_param = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>((q * r), lambda_max_params);
            vals_r__ = context__.vals_r("lambda_param");
            pos__ = 0;
            size_t lambda_param_j_2_max__ = lambda_max_params;
            size_t lambda_param_j_1_max__ = (q * r);
            for (size_t j_2__ = 0; j_2__ < lambda_param_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < lambda_param_j_1_max__; ++j_1__) {
                    lambda_param(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            // initialize transformed data variables
            current_statement_begin__ = 63;
            validate_non_negative_index("Q_x", "N", N);
            validate_non_negative_index("Q_x", "p", p);
            Q_x = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(N, p);
            stan::math::fill(Q_x, DUMMY_VAR__);
            current_statement_begin__ = 64;
            validate_non_negative_index("R_x", "p", p);
            validate_non_negative_index("R_x", "p", p);
            R_x = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(p, p);
            stan::math::fill(R_x, DUMMY_VAR__);
            current_statement_begin__ = 65;
            validate_non_negative_index("R_x_inverse", "p", p);
            validate_non_negative_index("R_x_inverse", "p", p);
            R_x_inverse = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(p, p);
            stan::math::fill(R_x_inverse, DUMMY_VAR__);
            current_statement_begin__ = 68;
            validate_non_negative_index("Q_z", "N", N);
            validate_non_negative_index("Q_z", "nk", nk);
            Q_z = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(N, nk);
            stan::math::fill(Q_z, DUMMY_VAR__);
            current_statement_begin__ = 69;
            validate_non_negative_index("R_z", "nk", nk);
            validate_non_negative_index("R_z", "nk", nk);
            R_z = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(nk, nk);
            stan::math::fill(R_z, DUMMY_VAR__);
            current_statement_begin__ = 70;
            validate_non_negative_index("R_z_inverse", "nk", nk);
            validate_non_negative_index("R_z_inverse", "nk", nk);
            R_z_inverse = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(nk, nk);
            stan::math::fill(R_z_inverse, DUMMY_VAR__);
            current_statement_begin__ = 73;
            validate_non_negative_index("qz", "N", N);
            validate_non_negative_index("qz", "max_col", max_col);
            validate_non_negative_index("qz", "q", q);
            qz = std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> >(q, Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(N, max_col));
            stan::math::fill(qz, DUMMY_VAR__);
            current_statement_begin__ = 74;
            validate_non_negative_index("rz", "max_col", max_col);
            validate_non_negative_index("rz", "max_col", max_col);
            validate_non_negative_index("rz", "q", q);
            rz = std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> >(q, Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(max_col, max_col));
            stan::math::fill(rz, DUMMY_VAR__);
            current_statement_begin__ = 75;
            validate_non_negative_index("rzinv", "max_col", max_col);
            validate_non_negative_index("rzinv", "max_col", max_col);
            validate_non_negative_index("rzinv", "q", q);
            rzinv = std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> >(q, Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(max_col, max_col));
            stan::math::fill(rzinv, DUMMY_VAR__);
            // execute transformed data statements
            current_statement_begin__ = 78;
            stan::math::assign(Q_x, multiply(stan::model::rvalue(qr_Q(X), stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_min_max(1, p), stan::model::nil_index_list())), "qr_Q(X)"), stan::math::sqrt((N - 1))));
            current_statement_begin__ = 79;
            stan::math::assign(R_x, divide(stan::model::rvalue(qr_R(X), stan::model::cons_list(stan::model::index_min_max(1, p), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "qr_R(X)"), stan::math::sqrt((N - 1))));
            current_statement_begin__ = 80;
            stan::math::assign(R_x_inverse, inverse(R_x));
            current_statement_begin__ = 83;
            stan::math::assign(Q_z, multiply(stan::model::rvalue(qr_Q(Z), stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_min_max(1, nk), stan::model::nil_index_list())), "qr_Q(Z)"), stan::math::sqrt((N - 1))));
            current_statement_begin__ = 84;
            stan::math::assign(R_z, divide(stan::model::rvalue(qr_R(Z), stan::model::cons_list(stan::model::index_min_max(1, nk), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "qr_R(Z)"), stan::math::sqrt((N - 1))));
            current_statement_begin__ = 85;
            stan::math::assign(R_z_inverse, inverse(R_z));
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 91;
            validate_non_negative_index("theta_b", "p", p);
            validate_non_negative_index("theta_b", "ny", ny);
            num_params_r__ += (p * ny);
            current_statement_begin__ = 95;
            validate_non_negative_index("tau", "nk", nk);
            validate_non_negative_index("tau", "ny", ny);
            num_params_r__ += (nk * ny);
            current_statement_begin__ = 98;
            validate_non_negative_index("lambda", "q", q);
            validate_non_negative_index("lambda", "ny", ny);
            num_params_r__ += (q * ny);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_multresponse_semipar_array_mixed_discrete() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 91;
        if (!(context__.contains_r("theta_b")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable theta_b missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("theta_b");
        pos__ = 0U;
        validate_non_negative_index("theta_b", "p", p);
        validate_non_negative_index("theta_b", "ny", ny);
        context__.validate_dims("parameter initialization", "theta_b", "vector_d", context__.to_vec(ny,p));
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > theta_b(ny, Eigen::Matrix<double, Eigen::Dynamic, 1>(p));
        size_t theta_b_j_1_max__ = p;
        size_t theta_b_k_0_max__ = ny;
        for (size_t j_1__ = 0; j_1__ < theta_b_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < theta_b_k_0_max__; ++k_0__) {
                theta_b[k_0__](j_1__) = vals_r__[pos__++];
            }
        }
        size_t theta_b_i_0_max__ = ny;
        for (size_t i_0__ = 0; i_0__ < theta_b_i_0_max__; ++i_0__) {
            try {
                writer__.vector_unconstrain(theta_b[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable theta_b: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 95;
        if (!(context__.contains_r("tau")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable tau missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("tau");
        pos__ = 0U;
        validate_non_negative_index("tau", "nk", nk);
        validate_non_negative_index("tau", "ny", ny);
        context__.validate_dims("parameter initialization", "tau", "vector_d", context__.to_vec(ny,nk));
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > tau(ny, Eigen::Matrix<double, Eigen::Dynamic, 1>(nk));
        size_t tau_j_1_max__ = nk;
        size_t tau_k_0_max__ = ny;
        for (size_t j_1__ = 0; j_1__ < tau_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < tau_k_0_max__; ++k_0__) {
                tau[k_0__](j_1__) = vals_r__[pos__++];
            }
        }
        size_t tau_i_0_max__ = ny;
        for (size_t i_0__ = 0; i_0__ < tau_i_0_max__; ++i_0__) {
            try {
                writer__.vector_unconstrain(tau[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable tau: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 98;
        if (!(context__.contains_r("lambda")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable lambda missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("lambda");
        pos__ = 0U;
        validate_non_negative_index("lambda", "q", q);
        validate_non_negative_index("lambda", "ny", ny);
        context__.validate_dims("parameter initialization", "lambda", "vector_d", context__.to_vec(ny,q));
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > lambda(ny, Eigen::Matrix<double, Eigen::Dynamic, 1>(q));
        size_t lambda_j_1_max__ = q;
        size_t lambda_k_0_max__ = ny;
        for (size_t j_1__ = 0; j_1__ < lambda_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < lambda_k_0_max__; ++k_0__) {
                lambda[k_0__](j_1__) = vals_r__[pos__++];
            }
        }
        size_t lambda_i_0_max__ = ny;
        for (size_t i_0__ = 0; i_0__ < lambda_i_0_max__; ++i_0__) {
            try {
                writer__.vector_lb_unconstrain(0, lambda[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable lambda: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 91;
            std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> > theta_b;
            size_t theta_b_d_0_max__ = ny;
            theta_b.reserve(theta_b_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < theta_b_d_0_max__; ++d_0__) {
                if (jacobian__)
                    theta_b.push_back(in__.vector_constrain(p, lp__));
                else
                    theta_b.push_back(in__.vector_constrain(p));
            }
            current_statement_begin__ = 95;
            std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> > tau;
            size_t tau_d_0_max__ = ny;
            tau.reserve(tau_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < tau_d_0_max__; ++d_0__) {
                if (jacobian__)
                    tau.push_back(in__.vector_constrain(nk, lp__));
                else
                    tau.push_back(in__.vector_constrain(nk));
            }
            current_statement_begin__ = 98;
            std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> > lambda;
            size_t lambda_d_0_max__ = ny;
            lambda.reserve(lambda_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < lambda_d_0_max__; ++d_0__) {
                if (jacobian__)
                    lambda.push_back(in__.vector_lb_constrain(0, q, lp__));
                else
                    lambda.push_back(in__.vector_lb_constrain(0, q));
            }
            // transformed parameters
            current_statement_begin__ = 104;
            validate_non_negative_index("theta_u", "nk", nk);
            validate_non_negative_index("theta_u", "ny", ny);
            std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> > theta_u(ny, Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1>(nk));
            stan::math::initialize(theta_u, DUMMY_VAR__);
            stan::math::fill(theta_u, DUMMY_VAR__);
            current_statement_begin__ = 105;
            validate_non_negative_index("yhat", "N", N);
            validate_non_negative_index("yhat", "ny", ny);
            std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> > yhat(ny, Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1>(N));
            stan::math::initialize(yhat, DUMMY_VAR__);
            stan::math::fill(yhat, DUMMY_VAR__);
            // transformed parameters block statements
            current_statement_begin__ = 108;
            for (int jj = 1; jj <= ny; ++jj) {
                current_statement_begin__ = 109;
                for (int l4 = 1; l4 <= 1; ++l4) {
                    {
                    current_statement_begin__ = 110;
                    int i(0);
                    (void) i;  // dummy to suppress unused var warning
                    stan::math::fill(i, std::numeric_limits<int>::min());
                    stan::math::assign(i,1);
                    current_statement_begin__ = 111;
                    for (int j4 = 1; j4 <= q; ++j4) {
                        current_statement_begin__ = 112;
                        for (int k4 = 1; k4 <= get_base1(zvars, j4, "zvars", 1); ++k4) {
                            current_statement_begin__ = 113;
                            stan::model::assign(theta_u, 
                                        stan::model::cons_list(stan::model::index_uni(jj), stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list())), 
                                        (get_base1(get_base1(tau, jj, "tau", 1), i, "tau", 2) * get_base1(get_base1(lambda, jj, "lambda", 1), j4, "lambda", 2)), 
                                        "assigning variable theta_u");
                            current_statement_begin__ = 114;
                            stan::math::assign(i, (i + 1));
                        }
                    }
                    }
                }
            }
            current_statement_begin__ = 121;
            for (int jj = 1; jj <= ny; ++jj) {
                current_statement_begin__ = 122;
                stan::model::assign(yhat, 
                            stan::model::cons_list(stan::model::index_uni(jj), stan::model::nil_index_list()), 
                            add(multiply(Q_x, get_base1(theta_b, jj, "theta_b", 1)), multiply(Q_z, get_base1(theta_u, jj, "theta_u", 1))), 
                            "assigning variable yhat");
            }
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 104;
            size_t theta_u_k_0_max__ = ny;
            size_t theta_u_j_1_max__ = nk;
            for (size_t k_0__ = 0; k_0__ < theta_u_k_0_max__; ++k_0__) {
                for (size_t j_1__ = 0; j_1__ < theta_u_j_1_max__; ++j_1__) {
                    if (stan::math::is_uninitialized(theta_u[k_0__](j_1__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: theta_u" << "[" << k_0__ << "]" << "(" << j_1__ << ")";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable theta_u: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            current_statement_begin__ = 105;
            size_t yhat_k_0_max__ = ny;
            size_t yhat_j_1_max__ = N;
            for (size_t k_0__ = 0; k_0__ < yhat_k_0_max__; ++k_0__) {
                for (size_t j_1__ = 0; j_1__ < yhat_j_1_max__; ++j_1__) {
                    if (stan::math::is_uninitialized(yhat[k_0__](j_1__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: yhat" << "[" << k_0__ << "]" << "(" << j_1__ << ")";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable yhat: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            // model body
            current_statement_begin__ = 140;
            for (int j1 = 1; j1 <= r; ++j1) {
                current_statement_begin__ = 141;
                for (int k1 = 1; k1 <= p; ++k1) {
                    current_statement_begin__ = 142;
                    if (as_bool(logical_eq(get_base1(betanum, (k1 * j1), "betanum", 1), 1))) {
                        current_statement_begin__ = 143;
                        lp_accum__.add(normal_log<propto__>(get_base1(get_base1(theta_b, j1, "theta_b", 1), k1, "theta_b", 2), get_base1(beta_param, (k1 * j1), 1, "beta_param", 1), get_base1(beta_param, (k1 * j1), 2, "beta_param", 1)));
                    } else if (as_bool(logical_eq(get_base1(betanum, k1, "betanum", 1), 2))) {
                        current_statement_begin__ = 145;
                        lp_accum__.add(student_t_log<propto__>(get_base1(get_base1(theta_b, j1, "theta_b", 1), k1, "theta_b", 2), get_base1(beta_param, (k1 * j1), 1, "beta_param", 1), get_base1(beta_param, (k1 * j1), 2, "beta_param", 1), get_base1(beta_param, (k1 * j1), 3, "beta_param", 1)));
                    }
                }
            }
            current_statement_begin__ = 149;
            for (int j1 = 1; j1 <= r; ++j1) {
                current_statement_begin__ = 150;
                for (int k1 = 1; k1 <= q; ++k1) {
                    current_statement_begin__ = 151;
                    if (as_bool(logical_eq(get_base1(lambdanum, (k1 * j1), "lambdanum", 1), 1))) {
                        current_statement_begin__ = 152;
                        lp_accum__.add(normal_log<propto__>(get_base1(get_base1(lambda, j1, "lambda", 1), k1, "lambda", 2), get_base1(lambda_param, (k1 * j1), 1, "lambda_param", 1), get_base1(lambda_param, (k1 * j1), 2, "lambda_param", 1)));
                    } else if (as_bool(logical_eq(get_base1(lambdanum, (k1 * j1), "lambdanum", 1), 2))) {
                        current_statement_begin__ = 154;
                        lp_accum__.add(student_t_log<propto__>(get_base1(get_base1(lambda, j1, "lambda", 1), k1, "lambda", 2), get_base1(lambda_param, (k1 * j1), 1, "lambda_param", 1), get_base1(lambda_param, (k1 * j1), 2, "lambda_param", 1), get_base1(lambda_param, (k1 * j1), 3, "lambda_param", 1)));
                    }
                }
            }
            current_statement_begin__ = 159;
            for (int jj = 1; jj <= ny; ++jj) {
                current_statement_begin__ = 160;
                lp_accum__.add(normal_log<propto__>(get_base1(tau, jj, "tau", 1), 0, 1));
            }
            current_statement_begin__ = 162;
            if (as_bool(logical_eq(famnum, 2))) {
                current_statement_begin__ = 163;
                for (int jj = 1; jj <= ny; ++jj) {
                    current_statement_begin__ = 165;
                    if (as_bool(logical_eq(linknum, 4))) {
                        current_statement_begin__ = 166;
                        lp_accum__.add(bernoulli_logit_log<propto__>(stan::model::rvalue(y, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(jj), stan::model::nil_index_list())), "y"), get_base1(yhat, jj, "yhat", 1)));
                    } else if (as_bool(logical_eq(linknum, 5))) {
                        current_statement_begin__ = 170;
                        lp_accum__.add(bernoulli_log<propto__>(stan::model::rvalue(y, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(jj), stan::model::nil_index_list())), "y"), Phi(get_base1(yhat, jj, "yhat", 1))));
                    } else if (as_bool(logical_eq(linknum, 6))) {
                        current_statement_begin__ = 174;
                        lp_accum__.add(bernoulli_log<propto__>(stan::model::rvalue(y, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(jj), stan::model::nil_index_list())), "y"), add(divide(stan::math::atan(get_base1(yhat, jj, "yhat", 1)), stan::math::pi()), 0.5)));
                    } else if (as_bool(logical_eq(linknum, 2))) {
                        current_statement_begin__ = 178;
                        lp_accum__.add(bernoulli_log<propto__>(stan::model::rvalue(y, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(jj), stan::model::nil_index_list())), "y"), stan::math::exp(get_base1(yhat, jj, "yhat", 1))));
                    } else if (as_bool(logical_eq(linknum, 7))) {
                        current_statement_begin__ = 182;
                        lp_accum__.add(bernoulli_log<propto__>(stan::model::rvalue(y, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(jj), stan::model::nil_index_list())), "y"), inv_cloglog(get_base1(yhat, jj, "yhat", 1))));
                    }
                }
            } else if (as_bool(logical_eq(famnum, 3))) {
                current_statement_begin__ = 186;
                for (int jj = 1; jj <= ny; ++jj) {
                    current_statement_begin__ = 188;
                    if (as_bool(logical_eq(linknum, 2))) {
                        current_statement_begin__ = 189;
                        lp_accum__.add(poisson_log_log<propto__>(stan::model::rvalue(y, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(jj), stan::model::nil_index_list())), "y"), get_base1(yhat, jj, "yhat", 1)));
                    } else if (as_bool(logical_eq(linknum, 1))) {
                        current_statement_begin__ = 192;
                        lp_accum__.add(poisson_log<propto__>(stan::model::rvalue(y, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(jj), stan::model::nil_index_list())), "y"), get_base1(yhat, jj, "yhat", 1)));
                    } else if (as_bool(logical_eq(linknum, 8))) {
                        current_statement_begin__ = 195;
                        lp_accum__.add(poisson_log<propto__>(stan::model::rvalue(y, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(jj), stan::model::nil_index_list())), "y"), square(get_base1(yhat, jj, "yhat", 1))));
                    }
                }
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("theta_b");
        names__.push_back("tau");
        names__.push_back("lambda");
        names__.push_back("theta_u");
        names__.push_back("yhat");
        names__.push_back("u");
        names__.push_back("beta");
        names__.push_back("log_lik");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(ny);
        dims__.push_back(p);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(ny);
        dims__.push_back(nk);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(ny);
        dims__.push_back(q);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(ny);
        dims__.push_back(nk);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(ny);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(ny);
        dims__.push_back(nk);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(ny);
        dims__.push_back(p);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(ny);
        dims__.push_back(N);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_multresponse_semipar_array_mixed_discrete_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > theta_b;
        size_t theta_b_d_0_max__ = ny;
        theta_b.reserve(theta_b_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < theta_b_d_0_max__; ++d_0__) {
            theta_b.push_back(in__.vector_constrain(p));
        }
        size_t theta_b_j_1_max__ = p;
        size_t theta_b_k_0_max__ = ny;
        for (size_t j_1__ = 0; j_1__ < theta_b_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < theta_b_k_0_max__; ++k_0__) {
                vars__.push_back(theta_b[k_0__](j_1__));
            }
        }
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > tau;
        size_t tau_d_0_max__ = ny;
        tau.reserve(tau_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < tau_d_0_max__; ++d_0__) {
            tau.push_back(in__.vector_constrain(nk));
        }
        size_t tau_j_1_max__ = nk;
        size_t tau_k_0_max__ = ny;
        for (size_t j_1__ = 0; j_1__ < tau_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < tau_k_0_max__; ++k_0__) {
                vars__.push_back(tau[k_0__](j_1__));
            }
        }
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > lambda;
        size_t lambda_d_0_max__ = ny;
        lambda.reserve(lambda_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < lambda_d_0_max__; ++d_0__) {
            lambda.push_back(in__.vector_lb_constrain(0, q));
        }
        size_t lambda_j_1_max__ = q;
        size_t lambda_k_0_max__ = ny;
        for (size_t j_1__ = 0; j_1__ < lambda_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < lambda_k_0_max__; ++k_0__) {
                vars__.push_back(lambda[k_0__](j_1__));
            }
        }
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 104;
            validate_non_negative_index("theta_u", "nk", nk);
            validate_non_negative_index("theta_u", "ny", ny);
            std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > theta_u(ny, Eigen::Matrix<double, Eigen::Dynamic, 1>(nk));
            stan::math::initialize(theta_u, DUMMY_VAR__);
            stan::math::fill(theta_u, DUMMY_VAR__);
            current_statement_begin__ = 105;
            validate_non_negative_index("yhat", "N", N);
            validate_non_negative_index("yhat", "ny", ny);
            std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > yhat(ny, Eigen::Matrix<double, Eigen::Dynamic, 1>(N));
            stan::math::initialize(yhat, DUMMY_VAR__);
            stan::math::fill(yhat, DUMMY_VAR__);
            // do transformed parameters statements
            current_statement_begin__ = 108;
            for (int jj = 1; jj <= ny; ++jj) {
                current_statement_begin__ = 109;
                for (int l4 = 1; l4 <= 1; ++l4) {
                    {
                    current_statement_begin__ = 110;
                    int i(0);
                    (void) i;  // dummy to suppress unused var warning
                    stan::math::fill(i, std::numeric_limits<int>::min());
                    stan::math::assign(i,1);
                    current_statement_begin__ = 111;
                    for (int j4 = 1; j4 <= q; ++j4) {
                        current_statement_begin__ = 112;
                        for (int k4 = 1; k4 <= get_base1(zvars, j4, "zvars", 1); ++k4) {
                            current_statement_begin__ = 113;
                            stan::model::assign(theta_u, 
                                        stan::model::cons_list(stan::model::index_uni(jj), stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list())), 
                                        (get_base1(get_base1(tau, jj, "tau", 1), i, "tau", 2) * get_base1(get_base1(lambda, jj, "lambda", 1), j4, "lambda", 2)), 
                                        "assigning variable theta_u");
                            current_statement_begin__ = 114;
                            stan::math::assign(i, (i + 1));
                        }
                    }
                    }
                }
            }
            current_statement_begin__ = 121;
            for (int jj = 1; jj <= ny; ++jj) {
                current_statement_begin__ = 122;
                stan::model::assign(yhat, 
                            stan::model::cons_list(stan::model::index_uni(jj), stan::model::nil_index_list()), 
                            add(multiply(Q_x, get_base1(theta_b, jj, "theta_b", 1)), multiply(Q_z, get_base1(theta_u, jj, "theta_u", 1))), 
                            "assigning variable yhat");
            }
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            // write transformed parameters
            if (include_tparams__) {
                size_t theta_u_j_1_max__ = nk;
                size_t theta_u_k_0_max__ = ny;
                for (size_t j_1__ = 0; j_1__ < theta_u_j_1_max__; ++j_1__) {
                    for (size_t k_0__ = 0; k_0__ < theta_u_k_0_max__; ++k_0__) {
                        vars__.push_back(theta_u[k_0__](j_1__));
                    }
                }
                size_t yhat_j_1_max__ = N;
                size_t yhat_k_0_max__ = ny;
                for (size_t j_1__ = 0; j_1__ < yhat_j_1_max__; ++j_1__) {
                    for (size_t k_0__ = 0; k_0__ < yhat_k_0_max__; ++k_0__) {
                        vars__.push_back(yhat[k_0__](j_1__));
                    }
                }
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 203;
            validate_non_negative_index("u", "nk", nk);
            validate_non_negative_index("u", "ny", ny);
            std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > u(ny, Eigen::Matrix<double, Eigen::Dynamic, 1>(nk));
            stan::math::initialize(u, DUMMY_VAR__);
            stan::math::fill(u, DUMMY_VAR__);
            current_statement_begin__ = 204;
            validate_non_negative_index("beta", "p", p);
            validate_non_negative_index("beta", "ny", ny);
            std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > beta(ny, Eigen::Matrix<double, Eigen::Dynamic, 1>(p));
            stan::math::initialize(beta, DUMMY_VAR__);
            stan::math::fill(beta, DUMMY_VAR__);
            current_statement_begin__ = 205;
            validate_non_negative_index("log_lik", "N", N);
            validate_non_negative_index("log_lik", "ny", ny);
            std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > log_lik(ny, Eigen::Matrix<double, Eigen::Dynamic, 1>(N));
            stan::math::initialize(log_lik, DUMMY_VAR__);
            stan::math::fill(log_lik, DUMMY_VAR__);
            // generated quantities statements
            current_statement_begin__ = 207;
            if (as_bool(logical_eq(qr, 1))) {
                current_statement_begin__ = 208;
                for (int jj = 1; jj <= ny; ++jj) {
                    current_statement_begin__ = 209;
                    stan::model::assign(beta, 
                                stan::model::cons_list(stan::model::index_uni(jj), stan::model::nil_index_list()), 
                                multiply(R_x_inverse, get_base1(theta_b, jj, "theta_b", 1)), 
                                "assigning variable beta");
                }
                current_statement_begin__ = 211;
                for (int jj = 1; jj <= ny; ++jj) {
                    current_statement_begin__ = 212;
                    stan::model::assign(u, 
                                stan::model::cons_list(stan::model::index_uni(jj), stan::model::nil_index_list()), 
                                multiply(R_z_inverse, get_base1(theta_u, jj, "theta_u", 1)), 
                                "assigning variable u");
                }
            } else {
                current_statement_begin__ = 216;
                for (int jj = 1; jj <= ny; ++jj) {
                    current_statement_begin__ = 218;
                    stan::model::assign(beta, 
                                stan::model::cons_list(stan::model::index_uni(jj), stan::model::nil_index_list()), 
                                get_base1(theta_b, jj, "theta_b", 1), 
                                "assigning variable beta");
                    current_statement_begin__ = 219;
                    stan::model::assign(u, 
                                stan::model::cons_list(stan::model::index_uni(jj), stan::model::nil_index_list()), 
                                get_base1(theta_u, jj, "theta_u", 1), 
                                "assigning variable u");
                }
            }
            current_statement_begin__ = 224;
            for (int jj = 1; jj <= ny; ++jj) {
                current_statement_begin__ = 225;
                for (int n = 1; n <= N; ++n) {
                    current_statement_begin__ = 227;
                    if (as_bool(logical_eq(famnum, 2))) {
                        current_statement_begin__ = 229;
                        if (as_bool(logical_eq(linknum, 4))) {
                            current_statement_begin__ = 230;
                            stan::model::assign(log_lik, 
                                        stan::model::cons_list(stan::model::index_uni(jj), stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list())), 
                                        bernoulli_logit_log(get_base1(y, n, "y", 1), (multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"), get_base1(beta, jj, "beta", 1)) + multiply(stan::model::rvalue(Z, stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "Z"), get_base1(u, jj, "u", 1)))), 
                                        "assigning variable log_lik");
                        } else if (as_bool(logical_eq(linknum, 5))) {
                            current_statement_begin__ = 233;
                            stan::model::assign(log_lik, 
                                        stan::model::cons_list(stan::model::index_uni(jj), stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list())), 
                                        bernoulli_log(get_base1(y, n, "y", 1), Phi((multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"), get_base1(beta, jj, "beta", 1)) + multiply(stan::model::rvalue(Z, stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "Z"), get_base1(u, jj, "u", 1))))), 
                                        "assigning variable log_lik");
                        } else if (as_bool(logical_eq(linknum, 6))) {
                            current_statement_begin__ = 236;
                            stan::model::assign(log_lik, 
                                        stan::model::cons_list(stan::model::index_uni(jj), stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list())), 
                                        bernoulli_log(get_base1(y, n, "y", 1), ((stan::math::atan((multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"), get_base1(beta, jj, "beta", 1)) + multiply(stan::model::rvalue(Z, stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "Z"), get_base1(u, jj, "u", 1)))) / stan::math::pi()) + 0.5)), 
                                        "assigning variable log_lik");
                        } else if (as_bool(logical_eq(linknum, 2))) {
                            current_statement_begin__ = 239;
                            stan::model::assign(log_lik, 
                                        stan::model::cons_list(stan::model::index_uni(jj), stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list())), 
                                        bernoulli_log(get_base1(y, n, "y", 1), stan::math::exp((multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"), get_base1(beta, jj, "beta", 1)) + multiply(stan::model::rvalue(Z, stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "Z"), get_base1(u, jj, "u", 1))))), 
                                        "assigning variable log_lik");
                        } else if (as_bool(logical_eq(linknum, 7))) {
                            current_statement_begin__ = 242;
                            stan::model::assign(log_lik, 
                                        stan::model::cons_list(stan::model::index_uni(jj), stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list())), 
                                        bernoulli_log(get_base1(y, n, "y", 1), inv_cloglog((multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"), get_base1(beta, jj, "beta", 1)) + multiply(stan::model::rvalue(Z, stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "Z"), get_base1(u, jj, "u", 1))))), 
                                        "assigning variable log_lik");
                        }
                    } else if (as_bool(logical_eq(famnum, 3))) {
                        current_statement_begin__ = 249;
                        if (as_bool(logical_eq(linknum, 2))) {
                            current_statement_begin__ = 250;
                            stan::model::assign(log_lik, 
                                        stan::model::cons_list(stan::model::index_uni(jj), stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list())), 
                                        poisson_log_log(get_base1(y, n, "y", 1), (multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"), get_base1(beta, jj, "beta", 1)) + multiply(stan::model::rvalue(Z, stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "Z"), get_base1(u, jj, "u", 1)))), 
                                        "assigning variable log_lik");
                        } else if (as_bool(logical_eq(linknum, 1))) {
                            current_statement_begin__ = 253;
                            stan::model::assign(log_lik, 
                                        stan::model::cons_list(stan::model::index_uni(jj), stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list())), 
                                        poisson_log(get_base1(y, n, "y", 1), (multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"), get_base1(beta, jj, "beta", 1)) + multiply(stan::model::rvalue(Z, stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "Z"), get_base1(u, jj, "u", 1)))), 
                                        "assigning variable log_lik");
                        } else if (as_bool(logical_eq(linknum, 8))) {
                            current_statement_begin__ = 256;
                            stan::model::assign(log_lik, 
                                        stan::model::cons_list(stan::model::index_uni(jj), stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list())), 
                                        poisson_log(get_base1(y, n, "y", 1), square((multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"), get_base1(beta, jj, "beta", 1)) + multiply(stan::model::rvalue(Z, stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "Z"), get_base1(u, jj, "u", 1))))), 
                                        "assigning variable log_lik");
                        }
                    }
                }
            }
            // validate, write generated quantities
            current_statement_begin__ = 203;
            size_t u_j_1_max__ = nk;
            size_t u_k_0_max__ = ny;
            for (size_t j_1__ = 0; j_1__ < u_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < u_k_0_max__; ++k_0__) {
                    vars__.push_back(u[k_0__](j_1__));
                }
            }
            current_statement_begin__ = 204;
            size_t beta_j_1_max__ = p;
            size_t beta_k_0_max__ = ny;
            for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < beta_k_0_max__; ++k_0__) {
                    vars__.push_back(beta[k_0__](j_1__));
                }
            }
            current_statement_begin__ = 205;
            size_t log_lik_j_1_max__ = N;
            size_t log_lik_k_0_max__ = ny;
            for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < log_lik_k_0_max__; ++k_0__) {
                    vars__.push_back(log_lik[k_0__](j_1__));
                }
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_multresponse_semipar_array_mixed_discrete";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t theta_b_j_1_max__ = p;
        size_t theta_b_k_0_max__ = ny;
        for (size_t j_1__ = 0; j_1__ < theta_b_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < theta_b_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "theta_b" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t tau_j_1_max__ = nk;
        size_t tau_k_0_max__ = ny;
        for (size_t j_1__ = 0; j_1__ < tau_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < tau_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "tau" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t lambda_j_1_max__ = q;
        size_t lambda_k_0_max__ = ny;
        for (size_t j_1__ = 0; j_1__ < lambda_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < lambda_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "lambda" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t theta_u_j_1_max__ = nk;
            size_t theta_u_k_0_max__ = ny;
            for (size_t j_1__ = 0; j_1__ < theta_u_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < theta_u_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "theta_u" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t yhat_j_1_max__ = N;
            size_t yhat_k_0_max__ = ny;
            for (size_t j_1__ = 0; j_1__ < yhat_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < yhat_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "yhat" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        if (!include_gqs__) return;
        size_t u_j_1_max__ = nk;
        size_t u_k_0_max__ = ny;
        for (size_t j_1__ = 0; j_1__ < u_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < u_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "u" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t beta_j_1_max__ = p;
        size_t beta_k_0_max__ = ny;
        for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < beta_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t log_lik_j_1_max__ = N;
        size_t log_lik_k_0_max__ = ny;
        for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < log_lik_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "log_lik" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t theta_b_j_1_max__ = p;
        size_t theta_b_k_0_max__ = ny;
        for (size_t j_1__ = 0; j_1__ < theta_b_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < theta_b_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "theta_b" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t tau_j_1_max__ = nk;
        size_t tau_k_0_max__ = ny;
        for (size_t j_1__ = 0; j_1__ < tau_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < tau_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "tau" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t lambda_j_1_max__ = q;
        size_t lambda_k_0_max__ = ny;
        for (size_t j_1__ = 0; j_1__ < lambda_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < lambda_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "lambda" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t theta_u_j_1_max__ = nk;
            size_t theta_u_k_0_max__ = ny;
            for (size_t j_1__ = 0; j_1__ < theta_u_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < theta_u_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "theta_u" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t yhat_j_1_max__ = N;
            size_t yhat_k_0_max__ = ny;
            for (size_t j_1__ = 0; j_1__ < yhat_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < yhat_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "yhat" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        if (!include_gqs__) return;
        size_t u_j_1_max__ = nk;
        size_t u_k_0_max__ = ny;
        for (size_t j_1__ = 0; j_1__ < u_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < u_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "u" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t beta_j_1_max__ = p;
        size_t beta_k_0_max__ = ny;
        for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < beta_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t log_lik_j_1_max__ = N;
        size_t log_lik_k_0_max__ = ny;
        for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < log_lik_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "log_lik" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
    }
}; // model
}  // namespace
typedef model_multresponse_semipar_array_mixed_discrete_namespace::model_multresponse_semipar_array_mixed_discrete stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
