# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("glm_continuous_mixed_with_qr", "glm_continuous_with_qr", "glm_discrete_mixed_with_qr", "glm_discrete_with_qr", "multresponse_semipar_array", "multresponse_semipar_array_discrete", "multresponse_semipar_array_mixed", "multresponse_semipar_array_mixed_discrete", "multresponse_semipar_array_mixed_randomint", "multresponse_semipar_array_mixed_randomint_discrete")

# load each stan module
Rcpp::loadModule("stan_fit4glm_continuous_mixed_with_qr_mod", what = TRUE)
Rcpp::loadModule("stan_fit4glm_continuous_with_qr_mod", what = TRUE)
Rcpp::loadModule("stan_fit4glm_discrete_mixed_with_qr_mod", what = TRUE)
Rcpp::loadModule("stan_fit4glm_discrete_with_qr_mod", what = TRUE)
Rcpp::loadModule("stan_fit4multresponse_semipar_array_mod", what = TRUE)
Rcpp::loadModule("stan_fit4multresponse_semipar_array_discrete_mod", what = TRUE)
Rcpp::loadModule("stan_fit4multresponse_semipar_array_mixed_mod", what = TRUE)
Rcpp::loadModule("stan_fit4multresponse_semipar_array_mixed_discrete_mod", what = TRUE)
Rcpp::loadModule("stan_fit4multresponse_semipar_array_mixed_randomint_mod", what = TRUE)
Rcpp::loadModule("stan_fit4multresponse_semipar_array_mixed_randomint_discrete_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("model_", model_name)))
})
